### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by jrivera32** [cisco-en-programmability/dnacenter_command_runner#1]
Hello, thank you for this. I have been using this script perfectly up until today when I started getting this error.

```Application "command_runner.py" Run Started
Traceback (most recent call last):
  File "/Users/jrivera1/Downloads/dnacenter_command_runner-master/command_runner.py", line 238, in <module>
    sys.exit(main(sys.argv[1], sys.argv[2]))
  File "/Users/jrivera1/Downloads/dnacenter_command_runner-master/command_runner.py", line 219, in main
    cli_commands_list = get_legit_cli_command_runner(dnac_token)
  File "/Users/jrivera1/Downloads/dnacenter_command_runner-master/command_runner.py", line 109, in get_legit_cli_command_runner
    cli_list = response_json['response']
KeyError: 'response'```

Not sure what to make of this, DNAC is on the most recent update. Any help would be appreciated. Thank you

**Comment by jrivera32** [comment]
Resolved. Looks like the REST Bundle needed to be restarted. I disabled and enabled from the DNAC GUI under Platform settings.

**Comment by zapodeanu** [comment]
thank you for the update
